apiVersion: apps/v1
kind: Deployment
metadata:
  # tên của deployment
  name: common-service
spec:
  # số POD tạo ra
  replicas: 2

  # thiết lập các POD do deploy quản lý, là POD có nhãn  "app=deployapp"
  selector:
    matchLabels:
      app: common-service

  # Định nghĩa mẫu POD, khi cần Deploy sử dụng mẫu này để tạo Pod
  template:
    metadata:
      name: pod-common-service
      labels:
        app: common-service
    spec:
      containers:
      - name: node-common-service
        image: daodinhcong2000/common-service:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 3500