apiVersion: v1
kind: Service
metadata:
  name: c-ecommerce-user-service
spec:
  selector:
    app: user-service
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: c-ecommerce-customer-service
spec:
  selector:
    app: customer-service
  type: ClusterIP
  ports:
    - port: 3200
      targetPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: c-ecommerce-seller-service
spec:
  selector:
    app: seller-service
  type: ClusterIP
  ports:
    - port: 3300
      targetPort: 3300
---
apiVersion: v1
kind: Service
metadata:
  name: c-ecommerce-admin-service
spec:
  selector:
    app: admin-service
  type: ClusterIP
  ports:
    - port: 3400
      targetPort: 3400
---
apiVersion: v1
kind: Service
metadata:
  name: c-ecommerce-common-service
spec:
  selector:
    app: common-service
  type: ClusterIP
  ports:
    - port: 3500
      targetPort: 3500
---
  apiVersion: v1
  kind: Service
  metadata:
    name: c-ecommerce-statistics-service
  spec:
    selector:
      app: statistics-service
    type: ClusterIP
    ports:
      - port: 3600
        targetPort: 3600

